name: Run Tests for React Native

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Clear Jest cache
        run: jest --clearCache

      - name: Run Tests
        run: jest --watchAll=false

      - name: Post-test cleanup
        run: echo "Cleanup completed"
